# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AviationNavigationDB
                                 A QGIS plugin
 Tools for dealing with aviation data in PostGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-05-19
        copyright            : (C) 2020 by Paweł Strzelewicz
        email                : @
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AviationNavigationDB class from file AviationNavigationDB.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .aviation_nav_db import AviationNavigationDB
    return AviationNavigationDB(iface)
